name: trigger jenkins job
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger single Job
      uses: GoldenspearLLC/build-jenkins-job@master
      with:
        jenkins-url: "http://localhost:8080/"
        user: "admin"
        jenkins-token: ${{ secrets.TOKEN }}
        job-path: "http://localhost:8080/job/job1/"
